spring:
  # app 이름
  application:
    name: board
  # DB연결 정보
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##board
    password: board1234

# 웹서버 포트
server:
  port: 9090


# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    root: info