spring:
  # app 이름
  application:
    name: board
  # DB연결 정보
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##board
    password: board1234
  #ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

# 웹서버 포트
server:
  port: 9090
# 서버 세션 타임아웃 설정
  servlet:
    session:
      timeout: 60
# 클라이언트의 세션아이디를 서버가 받는 방식
      tracking-mode: cookie

# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
#    root: info